services:
  triton:
    container_name: triton_rc
    image: nvcr.io/nvidia/tritonserver:24.01-py3
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    restart: no
    volumes:
      - ./triton_rc/models:/models
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip3 install --no-cache-dir transformers
        exec tritonserver --model-store=/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=none
      - PYTHONUNBUFFERED=1

  streamlit:
    container_name: streamlit_app
    image: python:3.10-slim
    ports:
      - 8501:8501
    volumes:
      - ./streamlit:/app
    working_dir: /app
    command:
      - bash
      - -c
      - |
        pip install --no-cache-dir streamlit numpy tritonclient[grpc]
        streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    depends_on:
      - triton
    environment:
      - PYTHONUNBUFFERED=1