version: '3.8'

services:
  triton:
    container_name: triton
    image: nvcr.io/nvidia/tritonserver:24.01-py3
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    restart: no
    volumes:
      - ./triton/models:/models
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip3 install --no-cache-dir transformers
        exec tritonserver --model-store=/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1